// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KnopsoAPIExample {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Label lblResponse;
		
		protected System.Web.UI.WebControls.HyperLink linkAction;
		
		protected System.Web.UI.WebControls.HyperLink linkActionAlt;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtUrl;
		
		protected System.Web.UI.WebControls.Button btnRequest;
	}
}
